server:
  http:
    port: 8081
  grpc:
    port: 9091
  name: "workflow-engine-2"

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "sam"
  dbname: "workflow_engine"
  sslmode: "disable"

logging:
  level: "info"